### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by Jambon1510** [rbw/pysnow#111]
Hello

**current behavior**
When I am disabling the SSL it works fine 
```
s = requests.Session()
s.proxies.update({'https': 'https://proxy_login:proxy_password@proxy:8080'})
s.auth = requests.auth.HTTPBasicAuth(user, pwd)
s.verify = False

# Create client object
c = pysnow.Client(instance=instance, session=s)

response = incident.get(query={'number': id_number})

```

however I want to make sure there is no security breach but when removing 
`s.verify = False`
I got the below message:

> requests.exceptions.SSLError: HTTPSConnectionPool(host='servicesitqualif.service-now.com', port=443): Max retries exceeded with url: /api/now/table/incident?sysparm_query=number%3DICD003279020&sysparm_limit=10000&sysparm_offset=0&sysparm_display_value=False&sysparm_suppress_pagination_header=False&sysparm_exclude_reference_link=False&sysparm_view=&sysparm_fields= (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')))

**expected behavior behavior**
Be able to instantiate the client and without disabling SSL

**Comment by rbw** [comment]
Hello!

Setting `requests.Session.verify` to False only disables *SSL Verification*.

You should be able to pass the path to a CA_BUNDLE file or directory with certificates of trusted CAs, if it's in a non-standard location.
`s.verify = '/path/to/certfile'`

Anyway, the problem here is that the Certificate used is considered invalid - this is an issue in your environment and has nothing to do with pysnow really. I'm guessing you're *not* getting these SSL errors when connecting without the proxy? And if that's the case, this is an issue with your proxy.

**Comment by phgogo** [comment]
In our case it helped to set an env-var to point the python requests module to the right CA-bundle:
```
REQUESTS_CA_BUNDLE: /etc/pki/tls/certs/ca-bundle.crt
```
