### ISSUE TITLE
Unauthorized Client 401

### ISSUE THREAD

**Issue by RealisticItem** [rbw/pysnow#125]
I'm trying to run the code given to fetch data:

```python
import pysnow

# Create client object
c = pysnow.Client(instance='TheBigCompanyInstance', user='MyActiveDirectoryUser', password='MyCoolPassword')

# Define a resource, here we'll use the incident table API
incident = c.resource(api_path='/table/task')

# Query for incidents with state 1
response = incident.get(query={'state': 1}, stream=True)

# Iterate over the result and print out `sys_id` of the matching records.
for record in response.all():
    print(record['sys_id'])
```
I get an Error: 

> HTTPError: 401 Client Error: Unauthorized for url: https://TheBigCompanyInstance.service-now.com/api/now/table/task?sysparm_query=state%3D1&sysparm_limit=10000&sysparm_offset=0&sysparm_display_value=False&sysparm_suppress_pagination_header=False&sysparm_exclude_reference_link=False&sysparm_view=&sysparm_fields=

When I take this particular link in my Browser, I can get the response. But not in my Python code. 

Is using an Active Directory user an issue to connect to ServiceNow with pysnow?
My company is using an SSO to connect to the multiple intern website, I'm not familiar with this technology, could it be a way to investigate?

**Comment by rbw** [comment]
Hello,

> Is using an Active Directory user an issue to connect to ServiceNow with pysnow?

Nope, it shouldn't be. However, the AD-derived objects could have some sort of restriction put on them. Also, make sure the username is in the correct format (this field is often mapped to email or such).

Anyway, I'd check the logs.

> My company is using an SSO to connect to the multiple intern website, I'm not familiar with this technology, could it be a way to investigate?

Other than the standard authentication method, pysnow also supports OAuth - is that what you're after?

If you actually mean using Kerberos and you're connecting to a ServiceNow instance outside your domain, then you'll probably need some sort of authentication proxy, because: [Kerberos_(protocol)#Drawbacks_and_limitations](https://en.wikipedia.org/wiki/Kerberos_(protocol)#Drawbacks_and_limitations).

**Comment by RealisticItem** [comment]
After some more information with my colleagues and yours, on Kerberos, I understand more the behavior I'm having.

> If you actually mean using Kerberos and you're connecting to a ServiceNow instance outside your domain, then you'll probably need some sort of authentication proxy, because: [Kerberos_(protocol)#Drawbacks_and_limitations](https://en.wikipedia.org/wiki/Kerberos_(protocol)#Drawbacks_and_limitations).

This is exaclty what made me have the error. Using a Proxy solved my issue.

Thank you for your responsiveness.
